
-- English (language_id = 1)
UPDATE service_translations
SET
  title = 'Web Development',
  short_description = 'Websites that perform and elevate your brand',
  long_description = '<p>At Advisable, we don''t just build websites, we create digital experiences that strengthen your brand''s presence, credibility, and performance.</p><p>By combining design, technology, and marketing, we deliver websites that are visually refined, highly functional, and aligned with your business goals.</p><h2>Our approach</h2><h3>1. Strategy &amp; UX Planning</h3><p>We start by analyzing your needs, audience, and goals. We design a user experience architecture (UX) that guides visitors toward meaningful actions.</p><h3>2. Conversion-Focused Design</h3><p>We craft clean, minimal, and responsive interfaces that showcase your brand while maximizing engagement and conversions.</p><h3>3. Development with Modern Technologies</h3><p>We use flexible platforms and frameworks to build fast, secure, and scalable solutions, from custom websites to e-commerce platforms.</p><h3>4. SEO &amp; Performance Optimization</h3><p>We optimize speed, structure, and content to ensure your site performs for both users and search engines.</p><h3>5. Integrations &amp; Scalability</h3><p>We integrate marketing, analytics, and CRM tools to make sure your website supports long-term business growth.</p><h2>The benefits for you</h2><ul><li>Websites built with strategy and purpose</li><li>High-end responsive design and user experience</li><li>Speed, security, and scalability for future growth</li><li>SEO-friendly structure that drives organic performance</li><li>Full support and optimization after launch</li></ul><h2>Why Advisable</h2><p>At Advisable, web development isn''t just a technical process, it''s part of your overall business strategy. We merge UX, technology, and performance marketing to build websites that don''t just look good, they deliver results.</p><h2>Next step</h2><p>Need a website that reflects your brand and drives measurable outcomes? Let''s design it together, strategically, creatively, and with growth in mind.</p>',
  seo_title = 'Web Development | Advisable',
  meta_description = 'Custom web development services by Advisable. We build fast, secure, SEO-optimized websites that elevate your brand and drive measurable business results.'
WHERE service_id = '2a62979d-5950-45b0-946b-5b884496de8c' AND language_id = 1;

-- Spanish (language_id = 2)
UPDATE service_translations
SET
  title = 'Web Development',
  short_description = 'Sitios web que generan resultados y fortalecen tu marca',
  long_description = '<p>En Advisable, no solo desarrollamos sitios web, creamos experiencias digitales que refuerzan la presencia, la credibilidad y el rendimiento de tu marca.</p><p>Combinamos diseño, tecnología y marketing para ofrecer sitios visualmente atractivos, funcionales y alineados con tus objetivos de negocio.</p><h2>Nuestro enfoque</h2><h3>1. Estrategia y Planificación UX</h3><p>Comenzamos analizando tus necesidades, tu audiencia y tus objetivos. Diseñamos una arquitectura de experiencia de usuario (UX) que guía al visitante hacia la acción deseada.</p><h3>2. Diseño enfocado en la conversión</h3><p>Creamos interfaces limpias, minimalistas y responsive que destacan tu marca y maximizan el engagement y las conversiones.</p><h3>3. Desarrollo con Tecnologías Modernas</h3><p>Utilizamos plataformas y frameworks flexibles para construir soluciones rápidas, seguras y escalables — desde sitios personalizados hasta plataformas e-commerce.</p><h3>4. Optimización SEO y de Rendimiento</h3><p>Optimizamos la velocidad, la estructura y el contenido para asegurar un rendimiento óptimo tanto para los usuarios como para los motores de búsqueda.</p><h3>5. Integraciones y Escalabilidad</h3><p>Integramos herramientas de marketing, analítica y CRM para que tu sitio web impulse el crecimiento sostenible de tu negocio.</p><h2>Los beneficios para ti</h2><ul><li>Sitios web diseñados con estrategia y propósito</li><li>Diseño responsive y experiencia de usuario de alto nivel</li><li>Velocidad, seguridad y escalabilidad garantizadas</li><li>Estructura SEO-friendly que mejora el rendimiento orgánico</li><li>Soporte y optimización continua después del lanzamiento</li></ul><h2>Por qué Advisable</h2><p>En Advisable, el desarrollo web no es solo un proceso técnico, es parte de tu estrategia empresarial. Combinamos UX, tecnología y performance marketing para crear sitios web que no solo se ven bien, sino que también generan resultados reales.</p><h2>Próximo paso</h2><p>¿Necesitas un sitio web que refleje tu marca y genere resultados medibles? Diseñémoslo juntos, con estrategia, creatividad y visión de crecimiento.</p>',
  seo_title = 'Web Development | Advisable',
  meta_description = 'Desarrollo web profesional por Advisable. Creamos sitios rápidos, seguros y optimizados para SEO que fortalecen tu marca y generan resultados medibles.'
WHERE service_id = '2a62979d-5950-45b0-946b-5b884496de8c' AND language_id = 2;

-- French (language_id = 3)
UPDATE service_translations
SET
  title = 'Web Development',
  short_description = 'Des sites web performants qui valorisent votre marque',
  long_description = '<p>Chez Advisable, nous ne créons pas simplement des sites web, nous concevons des expériences digitales qui renforcent la présence, la crédibilité et la performance de votre marque.</p><p>En combinant design, technologie et marketing, nous réalisons des sites à la fois esthétiques, fonctionnels et alignés sur vos objectifs commerciaux.</p><h2>Notre approche</h2><h3>1. Stratégie &amp; Planification UX</h3><p>Nous commençons par analyser vos besoins, votre audience et vos objectifs. Nous concevons une architecture d''expérience utilisateur (UX) qui guide les visiteurs vers l''action souhaitée.</p><h3>2. Design orienté conversion</h3><p>Nous créons des interfaces épurées, responsives et élégantes, conçues pour mettre en valeur votre marque et maximiser l''engagement et les conversions.</p><h3>3. Développement avec des technologies modernes</h3><p>Nous utilisons des plateformes et frameworks flexibles pour développer des solutions rapides, sécurisées et évolutives, des sites sur mesure jusqu''aux plateformes e-commerce.</p><h3>4. Optimisation SEO &amp; Performance</h3><p>Nous optimisons la vitesse, la structure et le contenu pour garantir une performance optimale, tant pour les utilisateurs que pour les moteurs de recherche.</p><h3>5. Intégrations &amp; Scalabilité</h3><p>Nous intégrons des outils de marketing, d''analytics et de CRM afin que votre site web soutienne votre croissance à long terme.</p><h2>Les bénéfices pour vous</h2><ul><li>Des sites web conçus avec stratégie et objectif clair</li><li>Design responsive et expérience utilisateur premium</li><li>Rapidité, sécurité et évolutivité garanties</li><li>Structure SEO-friendly pour une visibilité accrue</li><li>Accompagnement et optimisation continue après le lancement</li></ul><h2>Pourquoi Advisable</h2><p>Chez Advisable, le développement web n''est pas qu''un service technique, c''est une composante essentielle de votre stratégie globale. Nous combinons UX, technologie et performance marketing pour créer des sites web qui ne sont pas seulement beaux, mais surtout efficaces.</p><h2>Prochaine étape</h2><p>Vous souhaitez un site web qui reflète votre marque et génère de vrais résultats ? Concevons-le ensemble, avec stratégie, créativité et vision de croissance.</p>',
  seo_title = 'Web Development | Advisable',
  meta_description = 'Développement web sur mesure par Advisable. Nous créons des sites rapides, sécurisés et optimisés SEO qui valorisent votre marque et génèrent des résultats mesurables.'
WHERE service_id = '2a62979d-5950-45b0-946b-5b884496de8c' AND language_id = 3;

-- Greek (language_id = 5)
UPDATE service_translations
SET
  title = 'Web Development',
  short_description = 'Ιστοσελίδες που αποδίδουν και εξελίσσουν το brand σας',
  long_description = '<p>Στην Advisable, δε δημιουργούμε απλώς websites, δημιουργούμε ψηφιακές εμπειρίες που ενισχύουν την παρουσία, την αξιοπιστία και την απόδοση μιας επιχείρησης.</p><p>Συνδυάζουμε design, τεχνολογία και marketing, ώστε κάθε site να είναι αισθητικά άρτιο, λειτουργικό και προσαρμοσμένο στους στόχους σας.</p><h2>Η προσέγγισή μας</h2><h3>1. Στρατηγική &amp; UX Planning</h3><p>Ξεκινάμε με ανάλυση των αναγκών σας, του κοινού και των στόχων. Δημιουργούμε αρχιτεκτονική εμπειρίας (UX) που κατευθύνει τον επισκέπτη στη δράση.</p><h3>2. Design με Στόχο το Conversion</h3><p>Σχεδιάζουμε minimal, καθαρά και responsive interfaces που αναδεικνύουν το brand και οδηγούν σε υψηλότερα engagement &amp; conversions.</p><h3>3. Development με Σύγχρονες Τεχνολογίες</h3><p>Χρησιμοποιούμε ευέλικτες πλατφόρμες και frameworks για γρήγορη, ασφαλή και επεκτάσιμη ανάπτυξη, από custom websites μέχρι e-commerce λύσεις.</p><h3>4. SEO &amp; Performance Optimization</h3><p>Βελτιστοποιούμε την ταχύτητα, τη δομή και το περιεχόμενο ώστε το site να αποδίδει τόσο για τους χρήστες όσο και για τις μηχανές αναζήτησης.</p><h3>5. Integrations &amp; Scalability</h3><p>Ενσωματώνουμε εργαλεία marketing, analytics και CRM για να διασφαλίσουμε ότι το website υποστηρίζει την επιχειρηματική σας ανάπτυξη.</p><h2>Τα οφέλη για εσάς</h2><ul><li>Ιστοσελίδες σχεδιασμένες με στρατηγική και στόχο</li><li>Responsive design και εμπειρία χρήστη υψηλού επιπέδου</li><li>Ταχύτητα, ασφάλεια και δυνατότητα επεκτασιμότητας</li><li>SEO-friendly δομή που αυξάνει την οργανική απόδοση</li><li>Ολοκληρωμένη υποστήριξη μετά το λανσάρισμα</li></ul><h2>Γιατί Advisable</h2><p>Στην Advisable, το web development δεν είναι μια τεχνική υπηρεσία είναι κομμάτι της συνολικής στρατηγικής σας. Συνδυάζουμε UX, τεχνολογία και performance marketing για να δημιουργήσουμε websites που δεν είναι απλώς όμορφα, είναι αποδοτικά.</p>',
  seo_title = 'Web Development | Advisable',
  meta_description = 'Υπηρεσίες web development από την Advisable. Δημιουργούμε γρήγορες, ασφαλείς και SEO-optimized ιστοσελίδες που ενισχύουν το brand σας και φέρνουν μετρήσιμα αποτελέσματα.'
WHERE service_id = '2a62979d-5950-45b0-946b-5b884496de8c' AND language_id = 5;

-- Italian (language_id = 10)
UPDATE service_translations
SET
  title = 'Web Development',
  short_description = 'Siti web che performano e valorizzano il tuo brand',
  long_description = '<p>In Advisable non ci limitiamo a creare siti web: progettiamo esperienze digitali che rafforzano la presenza, la credibilità e le performance del tuo brand.</p><p>Combinando design, tecnologia e marketing, realizziamo siti web visivamente curati, altamente funzionali e allineati ai tuoi obiettivi di business.</p><h2>Il nostro approccio</h2><h3>1. Strategia e pianificazione UX</h3><p>Iniziamo analizzando le tue esigenze, il tuo pubblico e i tuoi obiettivi. Progettiamo un''architettura dell''esperienza utente (UX) che guida i visitatori verso azioni significative.</p><h3>2. Design orientato alla conversione</h3><p>Creiamo interfacce pulite, minimal e responsive che valorizzano il tuo brand massimizzando coinvolgimento e conversioni.</p><h3>3. Sviluppo con tecnologie moderne</h3><p>Utilizziamo piattaforme e framework flessibili per costruire soluzioni veloci, sicure e scalabili, dai siti web custom alle piattaforme e-commerce.</p><h3>4. Ottimizzazione SEO e delle performance</h3><p>Ottimizziamo velocità, struttura e contenuti per garantire che il tuo sito funzioni al meglio sia per gli utenti che per i motori di ricerca.</p><h3>5. Integrazioni e scalabilità</h3><p>Integriamo strumenti di marketing, analytics e CRM per assicurare che il tuo sito web supporti la crescita del business nel lungo periodo.</p><h2>I vantaggi per te</h2><ul><li>Siti web progettati con strategia e obiettivi chiari</li><li>Design e user experience di alto livello e responsive</li><li>Velocità, sicurezza e scalabilità per la crescita futura</li><li>Struttura SEO-friendly che favorisce le performance organiche</li><li>Supporto completo e ottimizzazione continua dopo il lancio</li></ul><h2>Perché Advisable</h2><p>In Advisable lo sviluppo web non è solo un processo tecnico, ma una parte integrante della tua strategia di business. Uniamo UX, tecnologia e performance marketing per creare siti web che non sono solo belli da vedere, ma che generano risultati concreti.</p><h2>Prossimo passo</h2><p>Hai bisogno di un sito web che rappresenti il tuo brand e produca risultati misurabili? Progettiamolo insieme, in modo strategico, creativo e orientato alla crescita.</p>',
  seo_title = 'Web Development | Advisable',
  meta_description = 'Sviluppo web professionale di Advisable. Creiamo siti veloci, sicuri e ottimizzati SEO che valorizzano il tuo brand e generano risultati di business misurabili.'
WHERE service_id = '2a62979d-5950-45b0-946b-5b884496de8c' AND language_id = 10;
