
-- Insert 6 FAQs for Adobe Experience Manager Agency
INSERT INTO service_faqs (id, service_id, display_order, is_active) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', '4e5a417b-e196-4353-9070-885b0ed19a9a', 1, true),
  ('a1b2c3d4-2222-4000-8000-000000000002', '4e5a417b-e196-4353-9070-885b0ed19a9a', 2, true),
  ('a1b2c3d4-3333-4000-8000-000000000003', '4e5a417b-e196-4353-9070-885b0ed19a9a', 3, true),
  ('a1b2c3d4-4444-4000-8000-000000000004', '4e5a417b-e196-4353-9070-885b0ed19a9a', 4, true),
  ('a1b2c3d4-5555-4000-8000-000000000005', '4e5a417b-e196-4353-9070-885b0ed19a9a', 5, true),
  ('a1b2c3d4-6666-4000-8000-000000000006', '4e5a417b-e196-4353-9070-885b0ed19a9a', 6, true);

-- EN (language_id = 1)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 1, 'What is Adobe Experience Manager (AEM) and why does my business need it?', 'Adobe Experience Manager (AEM) is an enterprise-grade Content Management System (CMS) and Digital Asset Management (DAM) platform by Adobe. It enables organizations to create, manage, and deliver personalized digital experiences across web, mobile, and other channels at scale. If your business requires complex content workflows, multi-site management, advanced personalization, or integration with the broader Adobe Experience Cloud ecosystem, AEM is the ideal solution.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 1, 'How long does a typical AEM implementation take?', 'A typical AEM implementation takes between 3 to 9 months depending on the project scope, number of sites, integration complexity, and customization requirements. A basic AEM Sites setup with standard templates can be delivered in 3-4 months, while enterprise-level deployments with custom workflows, multi-language support, and third-party integrations may take 6-9 months or longer.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 1, 'What is the difference between AEM as a Cloud Service and AEM On-Premise?', 'AEM as a Cloud Service is Adobe''s cloud-native version that offers automatic updates, built-in scalability, and reduced infrastructure management overhead. AEM On-Premise gives you full control over hosting and customization but requires dedicated IT resources for maintenance and upgrades. We help organizations evaluate both options and recommend the best deployment model based on their security requirements, budget, and technical capabilities.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 1, 'Can you migrate our existing website to Adobe Experience Manager?', 'Yes, we specialize in AEM migrations from platforms like WordPress, Drupal, Sitecore, and custom-built CMS solutions. Our migration process includes content audit and mapping, template design, asset migration, SEO preservation, and thorough QA testing to ensure zero downtime and no loss of search rankings during the transition.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 1, 'How does AEM integrate with other Adobe products and third-party tools?', 'AEM integrates natively with Adobe Experience Cloud products including Adobe Analytics, Adobe Target, Adobe Campaign, and Marketo Engage. It also supports integrations with third-party CRM systems like Salesforce and HubSpot, eCommerce platforms like Shopify and Magento, and marketing automation tools via REST APIs and webhooks. Our team designs and implements custom integration architectures tailored to your technology stack.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 1, 'What ongoing support and maintenance do you provide for AEM?', 'We offer comprehensive AEM support packages including 24/7 monitoring, security patching, performance optimization, content authoring support, and feature enhancements. Our managed services ensure your AEM platform stays up-to-date, secure, and performing optimally. We also provide training programs for your content teams to maximize their productivity with the platform.');

-- EL (language_id = 5)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 5, 'Τι είναι το Adobe Experience Manager (AEM) και γιατί το χρειάζεται η επιχείρησή μου;', 'Το Adobe Experience Manager (AEM) είναι μια enterprise-grade πλατφόρμα Content Management System (CMS) και Digital Asset Management (DAM) της Adobe. Επιτρέπει στους οργανισμούς να δημιουργούν, να διαχειρίζονται και να παρέχουν εξατομικευμένες ψηφιακές εμπειρίες σε web, mobile και άλλα κανάλια σε κλίμακα. Εάν η επιχείρησή σας απαιτεί σύνθετες ροές εργασίας περιεχομένου, multi-site management, προηγμένη εξατομίκευση ή integration με το ευρύτερο Adobe Experience Cloud ecosystem, το AEM είναι η ιδανική λύση.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 5, 'Πόσο χρόνο διαρκεί μια τυπική υλοποίηση AEM;', 'Μια τυπική υλοποίηση AEM διαρκεί μεταξύ 3 και 9 μηνών ανάλογα με το εύρος του project, τον αριθμό των sites, την πολυπλοκότητα των integrations και τις απαιτήσεις customization. Ένα βασικό AEM Sites setup με standard templates μπορεί να παραδοθεί σε 3 - 4 μήνες, ενώ enterprise-level deployments με custom workflows, multi-language υποστήριξη και third-party integrations μπορεί να χρειαστούν 6 - 9 μήνες ή περισσότερο.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 5, 'Ποια είναι η διαφορά μεταξύ AEM as a Cloud Service και AEM On-Premise;', 'Το AEM as a Cloud Service είναι η cloud-native έκδοση της Adobe που προσφέρει αυτόματες ενημερώσεις, ενσωματωμένη κλιμακωσιμότητα και μειωμένο κόστος διαχείρισης υποδομής. Το AEM On-Premise παρέχει πλήρη έλεγχο στο hosting και την προσαρμογή, αλλά απαιτεί αφοσιωμένους IT πόρους για συντήρηση και αναβαθμίσεις. Βοηθάμε τους οργανισμούς να αξιολογήσουν και τις δύο επιλογές και προτείνουμε το καλύτερο deployment model βάσει των απαιτήσεων ασφαλείας, του budget και των τεχνικών δυνατοτήτων τους.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 5, 'Μπορείτε να μεταφέρετε την υπάρχουσα ιστοσελίδα μας στο Adobe Experience Manager;', 'Ναι, ειδικευόμαστε σε AEM migrations από πλατφόρμες όπως WordPress, Drupal, Sitecore και custom-built CMS λύσεις. Η διαδικασία migration περιλαμβάνει content audit και mapping, σχεδιασμό templates, μεταφορά assets, διατήρηση SEO και ενδελεχές QA testing για να διασφαλιστεί μηδενικό downtime και καμία απώλεια search rankings κατά τη μετάβαση.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 5, 'Πώς ενσωματώνεται το AEM με άλλα προϊόντα Adobe και third-party εργαλεία;', 'Το AEM ενσωματώνεται native με προϊόντα του Adobe Experience Cloud, συμπεριλαμβανομένων των Adobe Analytics, Adobe Target, Adobe Campaign και Marketo Engage. Υποστηρίζει επίσης integrations με third-party CRM συστήματα όπως Salesforce και HubSpot, eCommerce πλατφόρμες όπως Shopify και Magento, και marketing automation εργαλεία μέσω REST APIs και webhooks. Η ομάδα μας σχεδιάζει και υλοποιεί custom integration αρχιτεκτονικές προσαρμοσμένες στο technology stack σας.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 5, 'Τι ongoing support και maintenance παρέχετε για το AEM;', 'Προσφέρουμε ολοκληρωμένα πακέτα AEM support που περιλαμβάνουν 24/7 monitoring, security patching, performance optimization, υποστήριξη content authoring και feature enhancements. Οι managed services μας διασφαλίζουν ότι η AEM πλατφόρμα σας παραμένει ενημερωμένη, ασφαλής και με βέλτιστη απόδοση. Παρέχουμε επίσης training προγράμματα για τις ομάδες περιεχομένου σας ώστε να μεγιστοποιήσουν την παραγωγικότητά τους με την πλατφόρμα.');

-- ES (language_id = 2)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 2, '¿Qué es Adobe Experience Manager (AEM) y por qué lo necesita mi empresa?', 'Adobe Experience Manager (AEM) es una plataforma enterprise-grade de Content Management System (CMS) y Digital Asset Management (DAM) de Adobe. Permite a las organizaciones crear, gestionar y ofrecer experiencias digitales personalizadas a través de web, mobile y otros canales a escala. Si su empresa requiere flujos de trabajo de contenido complejos, multi-site management, personalización avanzada o integración con el ecosistema más amplio de Adobe Experience Cloud, AEM es la solución ideal.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 2, '¿Cuánto tiempo tarda una implementación típica de AEM?', 'Una implementación típica de AEM tarda entre 3 y 9 meses dependiendo del alcance del proyecto, el número de sites, la complejidad de las integrations y los requisitos de customization. Una configuración básica de AEM Sites con templates estándar puede entregarse en 3-4 meses, mientras que deployments a nivel enterprise con custom workflows, soporte multi-language e integrations con terceros pueden tardar 6-9 meses o más.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 2, '¿Cuál es la diferencia entre AEM as a Cloud Service y AEM On-Premise?', 'AEM as a Cloud Service es la versión cloud-native de Adobe que ofrece actualizaciones automáticas, escalabilidad integrada y menor carga de gestión de infraestructura. AEM On-Premise le otorga control total sobre el hosting y la personalización, pero requiere recursos IT dedicados para mantenimiento y actualizaciones. Ayudamos a las organizaciones a evaluar ambas opciones y recomendamos el mejor modelo de deployment según sus requisitos de seguridad, presupuesto y capacidades técnicas.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 2, '¿Pueden migrar nuestro sitio web existente a Adobe Experience Manager?', 'Sí, nos especializamos en AEM migrations desde plataformas como WordPress, Drupal, Sitecore y soluciones CMS custom-built. Nuestro proceso de migration incluye content audit y mapping, diseño de templates, migración de assets, preservación de SEO y exhaustivo QA testing para garantizar cero downtime y ninguna pérdida de search rankings durante la transición.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 2, '¿Cómo se integra AEM con otros productos Adobe y herramientas de terceros?', 'AEM se integra de forma nativa con productos del Adobe Experience Cloud incluyendo Adobe Analytics, Adobe Target, Adobe Campaign y Marketo Engage. También soporta integrations con sistemas CRM de terceros como Salesforce y HubSpot, plataformas eCommerce como Shopify y Magento, y herramientas de marketing automation a través de REST APIs y webhooks. Nuestro equipo diseña e implementa arquitecturas de integration personalizadas adaptadas a su technology stack.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 2, '¿Qué soporte y mantenimiento continuo proporcionan para AEM?', 'Ofrecemos paquetes integrales de AEM support que incluyen monitoring 24/7, security patching, performance optimization, soporte de content authoring y feature enhancements. Nuestros managed services aseguran que su plataforma AEM se mantenga actualizada, segura y con rendimiento óptimo. También proporcionamos programas de training para sus equipos de contenido para maximizar su productividad con la plataforma.');

-- FR (language_id = 3)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 3, 'Qu''est-ce qu''Adobe Experience Manager (AEM) et pourquoi mon entreprise en a-t-elle besoin ?', 'Adobe Experience Manager (AEM) est une plateforme enterprise-grade de Content Management System (CMS) et de Digital Asset Management (DAM) d''Adobe. Elle permet aux organisations de créer, gérer et délivrer des expériences digitales personnalisées sur le web, le mobile et d''autres canaux à grande échelle. Si votre entreprise nécessite des workflows de contenu complexes, du multi-site management, une personnalisation avancée ou une intégration avec l''écosystème Adobe Experience Cloud, AEM est la solution idéale.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 3, 'Combien de temps prend une implémentation AEM typique ?', 'Une implémentation AEM typique prend entre 3 et 9 mois selon la portée du projet, le nombre de sites, la complexité des integrations et les exigences de customization. Une configuration AEM Sites de base avec des templates standards peut être livrée en 3-4 mois, tandis que les deployments enterprise avec des custom workflows, le support multi-language et des integrations tierces peuvent prendre 6-9 mois ou plus.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 3, 'Quelle est la différence entre AEM as a Cloud Service et AEM On-Premise ?', 'AEM as a Cloud Service est la version cloud-native d''Adobe qui offre des mises à jour automatiques, une scalabilité intégrée et une charge réduite de gestion d''infrastructure. AEM On-Premise vous donne un contrôle total sur l''hébergement et la personnalisation mais nécessite des ressources IT dédiées pour la maintenance et les mises à jour. Nous aidons les organisations à évaluer les deux options et recommandons le meilleur modèle de deployment selon leurs exigences de sécurité, leur budget et leurs capacités techniques.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 3, 'Pouvez-vous migrer notre site web existant vers Adobe Experience Manager ?', 'Oui, nous sommes spécialisés dans les AEM migrations depuis des plateformes comme WordPress, Drupal, Sitecore et des solutions CMS custom-built. Notre processus de migration comprend un content audit et mapping, la conception de templates, la migration d''assets, la préservation du SEO et des tests QA approfondis pour garantir zéro downtime et aucune perte de search rankings pendant la transition.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 3, 'Comment AEM s''intègre-t-il avec d''autres produits Adobe et des outils tiers ?', 'AEM s''intègre nativement avec les produits Adobe Experience Cloud, notamment Adobe Analytics, Adobe Target, Adobe Campaign et Marketo Engage. Il supporte également des integrations avec des systèmes CRM tiers comme Salesforce et HubSpot, des plateformes eCommerce comme Shopify et Magento, et des outils de marketing automation via des REST APIs et des webhooks. Notre équipe conçoit et implémente des architectures d''integration sur mesure adaptées à votre technology stack.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 3, 'Quel support et maintenance continus fournissez-vous pour AEM ?', 'Nous proposons des packages complets d''AEM support incluant le monitoring 24/7, le security patching, l''optimisation des performances, le support de content authoring et les feature enhancements. Nos managed services garantissent que votre plateforme AEM reste à jour, sécurisée et performante. Nous fournissons également des programmes de training pour vos équipes de contenu afin de maximiser leur productivité avec la plateforme.');

-- DE (language_id = 4)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 4, 'Was ist Adobe Experience Manager (AEM) und warum braucht mein Unternehmen es?', 'Adobe Experience Manager (AEM) ist eine enterprise-grade Plattform für Content Management System (CMS) und Digital Asset Management (DAM) von Adobe. Sie ermöglicht Organisationen, personalisierte digitale Erlebnisse über Web, Mobile und andere Kanäle in großem Maßstab zu erstellen, zu verwalten und bereitzustellen. Wenn Ihr Unternehmen komplexe Content-Workflows, Multi-Site Management, fortgeschrittene Personalisierung oder Integration mit dem breiteren Adobe Experience Cloud Ecosystem benötigt, ist AEM die ideale Lösung.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 4, 'Wie lange dauert eine typische AEM-Implementierung?', 'Eine typische AEM-Implementierung dauert zwischen 3 und 9 Monaten, abhängig vom Projektumfang, der Anzahl der Sites, der Integrationskomplexität und den Customization-Anforderungen. Ein grundlegendes AEM Sites Setup mit Standard-Templates kann in 3-4 Monaten geliefert werden, während Enterprise-Level Deployments mit Custom Workflows, Multi-Language-Unterstützung und Third-Party Integrations 6-9 Monate oder länger dauern können.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 4, 'Was ist der Unterschied zwischen AEM as a Cloud Service und AEM On-Premise?', 'AEM as a Cloud Service ist Adobes cloud-native Version, die automatische Updates, integrierte Skalierbarkeit und reduzierten Infrastruktur-Management-Aufwand bietet. AEM On-Premise gibt Ihnen volle Kontrolle über Hosting und Anpassung, erfordert aber dedizierte IT-Ressourcen für Wartung und Upgrades. Wir helfen Organisationen, beide Optionen zu evaluieren und empfehlen das beste Deployment-Modell basierend auf ihren Sicherheitsanforderungen, Budget und technischen Möglichkeiten.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 4, 'Können Sie unsere bestehende Website zu Adobe Experience Manager migrieren?', 'Ja, wir sind auf AEM Migrations von Plattformen wie WordPress, Drupal, Sitecore und Custom-Built CMS-Lösungen spezialisiert. Unser Migrationsprozess umfasst Content Audit und Mapping, Template-Design, Asset-Migration, SEO-Erhaltung und gründliches QA Testing, um null Downtime und keinen Verlust von Search Rankings während der Umstellung zu gewährleisten.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 4, 'Wie integriert sich AEM mit anderen Adobe-Produkten und Third-Party-Tools?', 'AEM integriert sich nativ mit Adobe Experience Cloud Produkten, einschließlich Adobe Analytics, Adobe Target, Adobe Campaign und Marketo Engage. Es unterstützt auch Integrations mit Third-Party CRM-Systemen wie Salesforce und HubSpot, eCommerce-Plattformen wie Shopify und Magento sowie Marketing Automation Tools über REST APIs und Webhooks. Unser Team entwirft und implementiert maßgeschneiderte Integration-Architekturen, die auf Ihren Technology Stack zugeschnitten sind.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 4, 'Welchen laufenden Support und Wartung bieten Sie für AEM?', 'Wir bieten umfassende AEM Support-Pakete einschließlich 24/7 Monitoring, Security Patching, Performance Optimization, Content Authoring Support und Feature Enhancements. Unsere Managed Services stellen sicher, dass Ihre AEM-Plattform aktuell, sicher und leistungsoptimiert bleibt. Wir bieten auch Training-Programme für Ihre Content-Teams an, um deren Produktivität mit der Plattform zu maximieren.');

-- IT (language_id = 10)
INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES
  ('a1b2c3d4-1111-4000-8000-000000000001', 10, 'Cos''è Adobe Experience Manager (AEM) e perché la mia azienda ne ha bisogno?', 'Adobe Experience Manager (AEM) è una piattaforma enterprise-grade di Content Management System (CMS) e Digital Asset Management (DAM) di Adobe. Consente alle organizzazioni di creare, gestire e offrire esperienze digitali personalizzate su web, mobile e altri canali su larga scala. Se la tua azienda richiede workflow di contenuto complessi, multi-site management, personalizzazione avanzata o integrazione con l''ecosistema più ampio di Adobe Experience Cloud, AEM è la soluzione ideale.'),
  ('a1b2c3d4-2222-4000-8000-000000000002', 10, 'Quanto tempo richiede un''implementazione tipica di AEM?', 'Un''implementazione tipica di AEM richiede tra 3 e 9 mesi a seconda dell''ambito del progetto, del numero di sites, della complessità delle integrations e dei requisiti di customization. Un setup base di AEM Sites con templates standard può essere consegnato in 3-4 mesi, mentre deployments a livello enterprise con custom workflows, supporto multi-language e integrations con terze parti possono richiedere 6-9 mesi o più.'),
  ('a1b2c3d4-3333-4000-8000-000000000003', 10, 'Qual è la differenza tra AEM as a Cloud Service e AEM On-Premise?', 'AEM as a Cloud Service è la versione cloud-native di Adobe che offre aggiornamenti automatici, scalabilità integrata e un overhead ridotto di gestione dell''infrastruttura. AEM On-Premise offre il controllo completo su hosting e personalizzazione, ma richiede risorse IT dedicate per manutenzione e aggiornamenti. Aiutiamo le organizzazioni a valutare entrambe le opzioni e raccomandiamo il miglior modello di deployment in base ai requisiti di sicurezza, al budget e alle capacità tecniche.'),
  ('a1b2c3d4-4444-4000-8000-000000000004', 10, 'Potete migrare il nostro sito web esistente su Adobe Experience Manager?', 'Sì, siamo specializzati in AEM migrations da piattaforme come WordPress, Drupal, Sitecore e soluzioni CMS custom-built. Il nostro processo di migration include content audit e mapping, progettazione di templates, migrazione degli assets, preservazione del SEO e approfonditi test di QA per garantire zero downtime e nessuna perdita di search rankings durante la transizione.'),
  ('a1b2c3d4-5555-4000-8000-000000000005', 10, 'Come si integra AEM con altri prodotti Adobe e strumenti di terze parti?', 'AEM si integra nativamente con i prodotti Adobe Experience Cloud tra cui Adobe Analytics, Adobe Target, Adobe Campaign e Marketo Engage. Supporta anche integrations con sistemi CRM di terze parti come Salesforce e HubSpot, piattaforme eCommerce come Shopify e Magento, e strumenti di marketing automation tramite REST APIs e webhooks. Il nostro team progetta e implementa architetture di integration personalizzate adattate al vostro technology stack.'),
  ('a1b2c3d4-6666-4000-8000-000000000006', 10, 'Che tipo di support e manutenzione continua fornite per AEM?', 'Offriamo pacchetti completi di AEM support che includono monitoring 24/7, security patching, performance optimization, supporto al content authoring e feature enhancements. I nostri managed services garantiscono che la vostra piattaforma AEM rimanga aggiornata, sicura e con prestazioni ottimali. Forniamo inoltre programmi di training per i vostri team di contenuto per massimizzare la loro produttività con la piattaforma.');
