
DO $$
DECLARE faq_id uuid;
BEGIN
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('20ec9f32-9817-4ffd-aef4-b48230111d66', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What does a digital marketing agency do?', 'A digital marketing agency plans and executes online strategies including SEO, PPC, social media, email, and content marketing to grow your business.'), (faq_id, 5, 'Τι κάνει ένα digital marketing agency;', 'Ένα digital marketing agency σχεδιάζει και υλοποιεί online στρατηγικές SEO, PPC, social media, email και content marketing για την ανάπτυξη της επιχείρησής σας.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('20ec9f32-9817-4ffd-aef4-b48230111d66', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much does a digital marketing agency cost?', 'Costs vary based on scope and services. Monthly retainers typically range from €2,000 to €15,000+ depending on channels and campaign complexity.'), (faq_id, 5, 'Πόσο κοστίζει ένα digital marketing agency;', 'Το κόστος εξαρτάται από τις υπηρεσίες. Τα μηνιαία πακέτα κυμαίνονται συνήθως από €2.000 έως €15.000+ ανάλογα με τα κανάλια.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('20ec9f32-9817-4ffd-aef4-b48230111d66', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How do I choose the right digital marketing agency?', 'Look for proven results in your industry, transparent reporting, strategic approach, and certifications like Google Premier Partner.'), (faq_id, 5, 'Πώς επιλέγω το σωστό digital marketing agency;', 'Αναζητήστε αποδεδειγμένα αποτελέσματα, διαφανείς αναφορές, στρατηγική προσέγγιση και πιστοποιήσεις όπως Google Premier Partner.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('20ec9f32-9817-4ffd-aef4-b48230111d66', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What results can I expect from a digital marketing agency?', 'Expect measurable improvements in traffic, leads, and revenue within 3-6 months, with ongoing optimization driving compounding growth.'), (faq_id, 5, 'Τι αποτελέσματα μπορώ να περιμένω;', 'Αναμένετε μετρήσιμες βελτιώσεις σε traffic, leads και έσοδα εντός 3-6 μηνών, με συνεχή βελτιστοποίηση.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('6bee1e67-d381-47fc-befb-e15f47878906', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is content marketing?', 'Content marketing is a strategic approach to creating and distributing valuable, relevant content to attract and retain a target audience.'), (faq_id, 5, 'Τι είναι το content marketing;', 'Το content marketing είναι μια στρατηγική δημιουργίας και διανομής πολύτιμου περιεχομένου για την προσέλκυση κοινού.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('6bee1e67-d381-47fc-befb-e15f47878906', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How long does content marketing take to show results?', 'Content marketing typically shows significant results within 6-12 months, with compounding returns.'), (faq_id, 5, 'Πόσο χρόνο χρειάζεται για αποτελέσματα;', 'Το content marketing δείχνει σημαντικά αποτελέσματα εντός 6-12 μηνών.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('6bee1e67-d381-47fc-befb-e15f47878906', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What types of content does a content marketing agency create?', 'We create blog posts, whitepapers, case studies, infographics, videos, podcasts, and newsletters.'), (faq_id, 5, 'Τι είδη περιεχομένου δημιουργεί;', 'Δημιουργούμε blog posts, whitepapers, case studies, infographics, videos, podcasts και newsletters.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('6bee1e67-d381-47fc-befb-e15f47878906', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How do you measure content marketing ROI?', 'We track organic traffic, lead generation, conversion rates, and revenue attribution.'), (faq_id, 5, 'Πώς μετράτε το ROI;', 'Παρακολουθούμε organic traffic, lead generation, conversion rates και revenue attribution.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ed6e8c7e-8c77-4343-b30e-8d9372d3f812', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What does a branding agency do?', 'A branding agency develops your brand strategy, visual identity, messaging, and guidelines.'), (faq_id, 5, 'Τι κάνει ένα branding agency;', 'Ένα branding agency αναπτύσσει τη στρατηγική, την οπτική ταυτότητα και τα μηνύματα του brand σας.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ed6e8c7e-8c77-4343-b30e-8d9372d3f812', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much does branding cost?', 'A complete branding project typically ranges from €5,000 to €50,000+.'), (faq_id, 5, 'Πόσο κοστίζει το branding;', 'Ένα ολοκληρωμένο branding project κυμαίνεται από €5.000 έως €50.000+.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ed6e8c7e-8c77-4343-b30e-8d9372d3f812', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'When should I rebrand my business?', 'Consider rebranding when your brand no longer reflects your values or your visual identity feels outdated.'), (faq_id, 5, 'Πότε πρέπει να κάνω rebrand;', 'Σκεφτείτε rebrand όταν το brand δεν αντικατοπτρίζει πλέον τις αξίες σας.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ed6e8c7e-8c77-4343-b30e-8d9372d3f812', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is included in a brand identity package?', 'Logo design, color palette, typography, brand guidelines, templates, and application examples.'), (faq_id, 5, 'Τι περιλαμβάνει ένα brand identity πακέτο;', 'Λογότυπο, χρωματική παλέτα, τυπογραφία, brand guidelines και templates.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('3cb33edf-89e8-441b-9789-0792fb3754f2', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much does video production cost?', 'Video production costs range from €1,500 for a simple social video to €20,000+ for a full brand film.'), (faq_id, 5, 'Πόσο κοστίζει η παραγωγή βίντεο;', 'Το κόστος κυμαίνεται από €1.500 για απλό social video έως €20.000+ για brand film.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('3cb33edf-89e8-441b-9789-0792fb3754f2', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What types of videos do you produce?', 'Brand videos, social media content, product demos, testimonials, explainer videos, and ad creative.'), (faq_id, 5, 'Τι είδη βίντεο παράγετε;', 'Brand videos, social media content, product demos, testimonials, explainer videos και ads.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('3cb33edf-89e8-441b-9789-0792fb3754f2', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How long does video production take?', 'A typical project takes 2-6 weeks from concept to delivery.'), (faq_id, 5, 'Πόσο χρόνο παίρνει η παραγωγή;', 'Ένα τυπικό project διαρκεί 2-6 εβδομάδες.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('3cb33edf-89e8-441b-9789-0792fb3754f2', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'Do you offer AI-powered video production?', 'Yes, we leverage AI tools for scriptwriting, editing, and generating video content at scale.'), (faq_id, 5, 'Προσφέρετε AI video production;', 'Ναι, αξιοποιούμε AI εργαλεία για scriptwriting, editing και video content σε κλίμακα.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('73b9df14-e062-4021-a454-88fd3e6378a4', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How do you select influencers for campaigns?', 'We use data-driven tools to analyze audience demographics, engagement rates, and brand fit.'), (faq_id, 5, 'Πώς επιλέγετε influencers;', 'Χρησιμοποιούμε data-driven εργαλεία για ανάλυση δημογραφικών και engagement rates.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('73b9df14-e062-4021-a454-88fd3e6378a4', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is the ROI of influencer marketing?', 'Influencer marketing delivers an average ROI of 5-7x.'), (faq_id, 5, 'Ποιο είναι το ROI του influencer marketing;', 'Το influencer marketing αποδίδει μέσο ROI 5-7x.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('73b9df14-e062-4021-a454-88fd3e6378a4', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much do influencer campaigns cost?', 'Costs vary from €500 for micro-influencer posts to €50,000+ for celebrity partnerships.'), (faq_id, 5, 'Πόσο κοστίζουν οι influencer καμπάνιες;', 'Από €500 για micro-influencer posts έως €50.000+ για celebrity partnerships.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('73b9df14-e062-4021-a454-88fd3e6378a4', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'Which platforms work best for influencer marketing?', 'Instagram, TikTok, and YouTube are the top platforms.'), (faq_id, 5, 'Ποιες πλατφόρμες λειτουργούν καλύτερα;', 'Instagram, TikTok και YouTube είναι οι κορυφαίες πλατφόρμες.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ef7f7c95-6b2f-481b-8b51-c168451ad5c6', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is conversion rate optimization?', 'CRO is the process of increasing the percentage of visitors who take a desired action.'), (faq_id, 5, 'Τι είναι το CRO;', 'Το CRO είναι η διαδικασία αύξησης του ποσοστού επισκεπτών που κάνουν μια επιθυμητή ενέργεια.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ef7f7c95-6b2f-481b-8b51-c168451ad5c6', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How quickly can CRO improve my revenue?', 'Many businesses see improvements within 4-8 weeks of implementing data-backed changes.'), (faq_id, 5, 'Πόσο γρήγορα βελτιώνει τα έσοδα;', 'Πολλές επιχειρήσεις βλέπουν βελτιώσεις εντός 4-8 εβδομάδων.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ef7f7c95-6b2f-481b-8b51-c168451ad5c6', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What tools do you use for CRO?', 'Google Optimize, VWO, Hotjar, FullStory, and custom analytics dashboards.'), (faq_id, 5, 'Τι εργαλεία χρησιμοποιείτε;', 'Google Optimize, VWO, Hotjar, FullStory και custom analytics dashboards.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('ef7f7c95-6b2f-481b-8b51-c168451ad5c6', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is a good conversion rate?', 'Average is 2-5%, top performers achieve 10%+. Depends on industry and traffic source.'), (faq_id, 5, 'Ποιο είναι ένα καλό conversion rate;', 'Μέσος όρος 2-5%, κορυφαίοι 10%+. Εξαρτάται από τη βιομηχανία.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('7dd3032c-6a14-4f89-bc96-52ac534fd969', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is the difference between UX and UI design?', 'UX focuses on user experience and journey, UI focuses on visual elements and interactive components.'), (faq_id, 5, 'Ποια η διαφορά UX και UI;', 'Το UX εστιάζει στην εμπειρία χρήστη, το UI στα οπτικά στοιχεία.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('7dd3032c-6a14-4f89-bc96-52ac534fd969', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much does UX/UI design cost?', 'Projects range from €5,000 for a simple app to €50,000+ for complex platforms.'), (faq_id, 5, 'Πόσο κοστίζει το UX/UI design;', 'Τα projects κυμαίνονται από €5.000 έως €50.000+.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('7dd3032c-6a14-4f89-bc96-52ac534fd969', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'Why is UX design important for business?', 'Good UX increases conversions, reduces support costs, and builds brand loyalty.'), (faq_id, 5, 'Γιατί είναι σημαντικό το UX design;', 'Καλό UX αυξάνει conversions, μειώνει κόστη υποστήριξης και χτίζει loyalty.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('7dd3032c-6a14-4f89-bc96-52ac534fd969', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'What is your UX design process?', 'Research, personas, journey mapping, wireframing, prototyping, usability testing, and iterative refinement.'), (faq_id, 5, 'Ποια είναι η UX design διαδικασία σας;', 'Research, personas, wireframing, prototyping και usability testing.');

  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('b471b215-d53d-4d3b-8c2a-43767e4ded3a', 1, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How much does mobile app development cost?', 'From €15,000 for a simple app to €150,000+ for complex enterprise applications.'), (faq_id, 5, 'Πόσο κοστίζει η ανάπτυξη mobile app;', 'Από €15.000 για απλό app έως €150.000+ για enterprise εφαρμογές.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('b471b215-d53d-4d3b-8c2a-43767e4ded3a', 2, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'Should I build a native or cross-platform app?', 'Cross-platform is great for most apps, native is best for performance-critical features.'), (faq_id, 5, 'Native ή cross-platform app;', 'Cross-platform για τα περισσότερα apps, native για performance-critical εφαρμογές.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('b471b215-d53d-4d3b-8c2a-43767e4ded3a', 3, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'How long does it take to build an app?', 'A typical mobile app takes 3-6 months from design to launch.'), (faq_id, 5, 'Πόσο χρόνο χρειάζεται;', 'Ένα τυπικό mobile app χρειάζεται 3-6 μήνες.');
  INSERT INTO service_faqs (service_id, display_order, is_active) VALUES ('b471b215-d53d-4d3b-8c2a-43767e4ded3a', 4, true) RETURNING id INTO faq_id;
  INSERT INTO service_faq_translations (faq_id, language_id, question, answer) VALUES (faq_id, 1, 'Do you provide app maintenance after launch?', 'Yes, including bug fixes, OS updates, performance monitoring, and feature enhancements.'), (faq_id, 5, 'Παρέχετε maintenance μετά το launch;', 'Ναι, με bug fixes, OS updates, performance monitoring και νέα features.');
END $$;
