// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://difvvdmelbtjxxvpjuvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZnZ2ZG1lbGJ0anh4dnBqdXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Mjk3OTEsImV4cCI6MjA1OTIwNTc5MX0.S6W1tGt-ZCW_Vd3H-rz7uaCfjW_WpYJxk9f4d-z-Ojg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});